In [2]:
import tarfile
import numpy as np
import os
import pandas as pd
import matplotlib.pyplot as plt
import scipy
import pickle

In [43]:
master_dict = {}

### hc-2

In [44]:
dataset = 'hc2'
master_dict[dataset] = {}

In [47]:
session = 'ec013.527'
master_dict[dataset][session] = {}

In [4]:
file =r'C:\Users\miles\Projects\datasets\crcns\hc2\ec013.527\ec013.527.clu.1'
os.path.abspath('C:\\Users\\miles\\Projects\\datasets')

'C:\\Users\\miles\\Projects\\datasets'

In [5]:
def get_data(clusters_file, spikes_file):
#     labels_file = open(labels_file)
    clusters = clusters_file.readlines()
    num_clu = int(clusters[0][:-1])-2
#     num_clu = clusters[0][:-1]
    clusters = np.array([k[:-1] for k in clusters],dtype='int')[1:]
#     labels = np.array([k[:-1] for k in labels])
    
    spikes = spikes_file.readlines()
    spikes = np.array([k[:-1] for k in spikes],dtype='float')
    
    spikes = spikes[clusters>1]
    clusters = clusters[clusters>1]
    
    spikes, clusters = spikes[spikes.argsort()], clusters[spikes.argsort()] # sorting the arrays by spike time
    
    
    return clusters, spikes, num_clu


In [33]:
spikes[0], clusters[0]

(array([   3150,    3957,    5109, ..., 1058318, 1058344, 1058347]),
 array([ 7, 11, 12, ..., 12, 12, 12]))

In [6]:
shanks = 4

In [48]:
clusters, spikes, num_clu = [],[],[]

for i in range(shanks):
    (clusters_file, spikes_file) = (
        open(f"C:\\Users\\miles\\Projects\\datasets\\crcns\\hc2\\ec013.527\\ec013.527.clu.{i+1}"),
        open(f"C:\\Users\miles\\Projects\\datasets\\crcns\\hc2\\ec013.527\\ec013.527.res.{i+1}")
    )
    a,b,c = get_data(clusters_file, spikes_file)
    a,b = a.astype(int), (b/20).astype(int)
    clusters.append(a)
    spikes.append(b)
    num_clu.append(c)
    master_dict[dataset][session][i] = {}
    master_dict[dataset][session][i]['raster'] = (b,a)
    master_dict[dataset][session]['surrogate'] = (None)
      

In [49]:
master_dict

{'hc2': {'ec013.527': {0: {'raster': (array([   3150,    3957,    5109, ..., 1058318, 1058344, 1058347]),
     array([ 7, 11, 12, ..., 12, 12, 12]))},
   'surrogate': None,
   1: {'raster': (array([      7,      53,      76, ..., 1059719, 1059734, 1059969]),
     array([ 6,  4,  4, ...,  4, 10,  4]))},
   2: {'raster': (array([      2,      25,      53, ..., 1059919, 1059937, 1059985]),
     array([5, 5, 4, ..., 5, 5, 5]))},
   3: {'raster': (array([   3953,    5431,    7545, ..., 1059634, 1059901, 1060090]),
     array([4, 3, 5, ..., 4, 4, 4]))}}}}

### ac-3
Big Dataset!!!

In [50]:
dataset = 'ac3'
master_dict[dataset] = {}
master_dict

{'hc2': {'ec013.527': {0: {'raster': (array([   3150,    3957,    5109, ..., 1058318, 1058344, 1058347]),
     array([ 7, 11, 12, ..., 12, 12, 12]))},
   'surrogate': None,
   1: {'raster': (array([      7,      53,      76, ..., 1059719, 1059734, 1059969]),
     array([ 6,  4,  4, ...,  4, 10,  4]))},
   2: {'raster': (array([      2,      25,      53, ..., 1059919, 1059937, 1059985]),
     array([5, 5, 4, ..., 5, 5, 5]))},
   3: {'raster': (array([   3953,    5431,    7545, ..., 1059634, 1059901, 1060090]),
     array([4, 3, 5, ..., 4, 4, 4]))}}},
 'ac3': {}}

In [55]:
filenames = os.listdir(r'C:\Users\miles\Projects\datasets\crcns\ac3\Data')
import scipy.io
test = [scipy.io.loadmat(r'C:\Users\miles\Projects\datasets\crcns\ac3\Data\\'+k) for k in filenames]
df = pd.DataFrame(test[0]['spk'][0])
fs = 20 # Sampling rate in kHz
num_units = test[0]['spk'][0]['spiketimes'].shape[0]
spikes = np.array([])
labels = np.array([])
for i in range(num_units):
    spikes = np.hstack((spikes,test[0]['spk'][0]['spiketimes'][i].squeeze()))
    labels = np.hstack((labels,i*np.ones_like(test[0]['spk'][0]['spiketimes'][i].squeeze())))
spikes, labels = spikes[spikes.argsort()], labels[spikes.argsort()] # sorting the arrays by spike time
spikes = np.round(spikes).astype(int)
labels = labels.astype(int)
print(spikes.shape,labels.shape)

(72240,) (72240,)


In [57]:
session = 1
shank = 1
master_dict[dataset][session] = {}
master_dict[dataset][session][shank] = {}

In [52]:
import simulate_data, scan

In [61]:
scan.scan_raster(spikes,labels,window_dim=50)

72076 Windows
121 patterns found..... 99% 10.01 | opt_cutoff - 4.62 | most_detections - 126ections - 1260


([array([[ 0, 22],
         [ 4,  7],
         [ 4,  9],
         [ 6,  0],
         [13, 21],
         [13, 22],
         [28, 21],
         [28, 27],
         [28, 29]]),
  array([[ 0, 21],
         [15, 21],
         [19, 21],
         [23,  1],
         [23,  9],
         [26, 21],
         [26, 28]]),
  array([[ 0,  1],
         [ 8, 27],
         [ 8, 28],
         [ 8, 29],
         [11, 29],
         [14,  1]]),
  array([[ 0,  1],
         [ 5,  0],
         [ 5,  2],
         [ 6, 12],
         [21,  1],
         [22, 27],
         [22, 28],
         [22, 29],
         [34, 28]]),
  array([[0, 1],
         [4, 1]]),
  array([[0, 9],
         [8, 1]]),
  array([[ 0, 22],
         [ 5,  1]]),
  array([[0, 1],
         [1, 4]]),
  array([[ 0, 21],
         [17,  1]]),
  array([[0, 5],
         [0, 8]]),
  array([[0, 5],
         [0, 9]]),
  array([[0, 5],
         [0, 9]]),
  array([[0, 5],
         [0, 8]]),
  array([[ 0,  5],
         [80,  6],
         [80,  9]]),
  array([[0,

In [62]:
pattern_template, all_times, window_time, cluster_time, sequence_time = _

In [64]:
np.array([len(k) for k in pattern_template]), np.array([len(k) for k in all_times])

(array([9, 7, 6, 9, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2, 4, 4, 3, 3,
        3, 2, 3, 2, 3, 2, 2, 4, 3, 4, 3, 4, 3, 3, 2, 3, 3, 2, 4, 3, 4, 4,
        3, 2, 4, 2, 4, 4, 5, 3, 3, 3, 2, 4, 5, 5, 4, 5, 3, 3, 3, 4, 3, 7,
        5, 2, 2, 2, 3, 2, 3, 4, 4, 3, 4, 2, 4, 3, 4, 5, 4, 3, 5, 4, 3, 3,
        2, 3, 3, 4, 5, 4, 4, 3, 4, 3, 3, 4, 4, 4, 4, 4, 3, 3, 3, 4, 4, 4,
        5, 3, 4, 3, 3, 3, 4, 3, 4, 3, 3]),
 array([  2,   2,   2,   2,   2,   2,   2,   2,   2,   6,   5,   2,   2,
          2,   2,   3,   2,   3,   2,   4,   2,   7,   5,  27,   2,   6,
         23,   8,  13,   4,   4,  10,   2,   4,   2,   4,   2,   6,   3,
          6,   4, 117,   3,   8,   3,  16,   2,   2,   7,   2,   3, 127,
          2,   8,   4,  13,   7,   8,   7,   2,   2,   6,   4,   2,   2,
          2,   3,   2,   3,   3,  31,   2,   6,   2,   4,  90,   6,   4,
          3,  53,   3,   3,   2,  54,   4,  11,  19,   4,  12,  54,  10,
         10,   9,  16,   3,   4,   4,   3,   2,   7,  10,  24,   6,   2,
   

In [65]:
window_time, cluster_time, sequence_time

(567.0818734169006, 38081.088411569595, 2.0741214752197266)

In [71]:
def sparse_convolution(spikes,labels, pattern_):
    # Extract unique channels from the pattern
    pattern = pattern_.copy()
    filt_labels = pattern.T[1]
    filt_spikes = spikes[np.isin(labels, filt_labels)]
    filt_labels = labels[np.isin(labels, filt_labels)]
    set_raster = set([(a,b) for a,b in zip(filt_spikes,filt_labels)])
    out = np.zeros((1+np.max(spikes)))
    t=0
    while t <= (np.max(spikes)):
        pattern.T[0]+=1
        set_pattern = set([tuple(k) for k in pattern])
        out[t] = len(set_pattern.intersection(set_raster))/len(set_pattern)
        t+=1
                
    return out



In [74]:
from tqdm import tqdm

In [75]:
sanity_check = []
for k in tqdm(pattern_template):
    sanity_check.append(sparse_convolution(spikes,labels, k))

100%|██████████████████████████████████████████████████████████████████████████████| 121/121 [1:08:00<00:00, 33.72s/it]


In [77]:
sanity_check = np.array(sanity_check).T

In [78]:
counts = np.array([list(np.where(sanity_check==1)[1]).count(k) for k in np.unique(np.where(sanity_check==1)[1])])
patterns = np.unique(np.where(sanity_check==1)[1])
pattern_template = np.array(pattern_template,dtype='object')
np.array(patterns[counts>=3]), np.array(counts[counts>=3]), np.array([len(k) for k in pattern_template[patterns[counts>=3]]])

(array([  4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,  16,
         17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,
         30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,
         43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,
         56,  57,  58,  59,  60,  61,  62,  63,  64,  66,  67,  68,  69,
         70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,
         83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,
         96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108,
        109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120],
       dtype=int64),
 array([ 162,   89,   88,  274,   91,  192,  463,  463,  192,    3,  201,
         147,  355,  469,  135,   20,  385,  385,  360, 2174,   72, 2174,
        1901, 2174, 2174,  315,  101,  315,  360,  315,  183,  101, 2342,
         130,  127, 2841,  135, 2383,  123,  123,  152, 2863,    5,  672,
          91,   12,   17, 2383

In [79]:
np.array(patterns[counts>=5]), np.array(counts[counts>=5]), np.array([len(k) for k in pattern_template[patterns[counts>=5]]])

(array([  4,   5,   6,   7,   8,   9,  10,  11,  12,  14,  15,  16,  17,
         18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,
         31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,
         44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,
         57,  58,  59,  60,  61,  62,  63,  64,  67,  68,  69,  70,  71,
         72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84,
         85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,
         98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110,
        111, 112, 113, 114, 115, 116, 117, 118, 119, 120], dtype=int64),
 array([ 162,   89,   88,  274,   91,  192,  463,  463,  192,  201,  147,
         355,  469,  135,   20,  385,  385,  360, 2174,   72, 2174, 1901,
        2174, 2174,  315,  101,  315,  360,  315,  183,  101, 2342,  130,
         127, 2841,  135, 2383,  123,  123,  152, 2863,    5,  672,   91,
          12,   17, 2383,  127,  130, 2841,  12

In [ ]:
pattern_template[]

In [67]:
a = {
    'pattern_template':pattern_template,
    'all_times':all_times, 
    'window_time':window_time, 
    'cluster_time':cluster_time, 
    'sequence_time':sequence_time
}

In [68]:
import pickle

In [69]:
with open('hugeac3.pickle', 'wb') as handle:
    pickle.dump(a, handle, protocol=pickle.HIGHEST_PROTOCOL)